name: Atualizar contratos 24 25

on:
    workflow_run:
      workflows: ["Atualizar contratos 23 24 2"]
      types:
        - completed
    workflow_dispatch:
jobs:
    update-data:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install requests

            - name: Run update script 2024-2025
              run: python Dados/Coleta_dados/coleta_api.py "20240102" "20250101" "a" "\n" ","

            - name: Commit and push changes
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --global user.name 'GitHub Actions'
                git config --global user.email 'noreply.github.com'
                git pull origin main
                git add .
                git commit -m "Atualização automática: $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nada para commitar"
                git push
               
