name: Tratar erros

on:
  workflow_run:
    workflows: ["Atualizar contratos 25 26"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-cnpjs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run ERROS script
        run: python Dados/Coleta_dados/coleta_contratosERRO.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply.github.com'
          git pull origin main
          git add .
          git commit -m "Atualização automática: $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nada para commitar"
          git push origin main
        
      - name: Notify via GitHub Issue
        uses: actions/github-script@v6
        with:
         script: |
          await github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Novo arquivo de contratos gerado",
            body: "O arquivo `contratos_OFICIAL_versao3.json` foi gerado. Execute o workflow de renomeação quando estiver pronto para revisão.",
            assignees: ["davi-aguiar-vieira", "mat054"]
          });